# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rexample.proto\x12\x07\x65xample\"\'\n\x07Request\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0b\n\x03num\x18\x02 \x01(\x05\")\n\x08Response\x12\r\n\x05reply\x18\x01 \x01(\t\x12\x0e\n\x06re_num\x18\x02 \x01(\x05\x32\x44\n\x0e\x45xampleService\x12\x32\n\x0bSendMessage\x12\x10.example.Request\x1a\x11.example.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUEST']._serialized_start=26
  _globals['_REQUEST']._serialized_end=65
  _globals['_RESPONSE']._serialized_start=67
  _globals['_RESPONSE']._serialized_end=108
  _globals['_EXAMPLESERVICE']._serialized_start=110
  _globals['_EXAMPLESERVICE']._serialized_end=178
# @@protoc_insertion_point(module_scope)
